language: python
sudo: false

matrix:
  include:

    # Linting
    - python: 2.7
      env: SCRIPT=lint
    - python: 3.6
      env: SCRIPT=lint

    # Black
    - python: 3.6-dev
      env: SCRIPT=black

    # Packaging
    - python: 3.6-dev
      env: SCRIPT=packaging

    # Unit tests
    - python: 2.7
      env: SCRIPT=tests

    - python: 3.4
      env: SCRIPT=tests

    - python: 3.5
      env: SCRIPT=tests

    - python: 3.6-dev
      env: SCRIPT=tests

    - python: 3.7-dev
      env: SCRIPT=tests

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - python -m pip install -r dev-requirements.txt -r requirements.txt

script:
  - chmod a+x ./.travis/script.sh
  - ./.travis/script.sh

after_success:
  - |
    if [ "$SCRIPT" = "tests" ]; then
        codecov
    fi

notifications:
  email: false

branches:
  only:
  - master
